# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scenario.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scenario.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0escenario.proto\"\x15\n\x05\x44Pong\x12\x0c\n\x04name\x18\x01 \x01(\t2(\n\x08Scenario\x12\x1c\n\x04\x43hat\x12\x06.DPong\x1a\x06.DPong\"\x00(\x01\x30\x01\x62\x06proto3')
)




_DPONG = _descriptor.Descriptor(
  name='DPong',
  full_name='DPong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DPong.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=39,
)

DESCRIPTOR.message_types_by_name['DPong'] = _DPONG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DPong = _reflection.GeneratedProtocolMessageType('DPong', (_message.Message,), dict(
  DESCRIPTOR = _DPONG,
  __module__ = 'scenario_pb2'
  # @@protoc_insertion_point(class_scope:DPong)
  ))
_sym_db.RegisterMessage(DPong)



_SCENARIO = _descriptor.ServiceDescriptor(
  name='Scenario',
  full_name='Scenario',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=41,
  serialized_end=81,
  methods=[
  _descriptor.MethodDescriptor(
    name='Chat',
    full_name='Scenario.Chat',
    index=0,
    containing_service=None,
    input_type=_DPONG,
    output_type=_DPONG,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCENARIO)

DESCRIPTOR.services_by_name['Scenario'] = _SCENARIO

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class ScenarioStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Chat = channel.stream_stream(
          '/Scenario/Chat',
          request_serializer=DPong.SerializeToString,
          response_deserializer=DPong.FromString,
          )


  class ScenarioServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Chat(self, request_iterator, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ScenarioServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Chat': grpc.stream_stream_rpc_method_handler(
            servicer.Chat,
            request_deserializer=DPong.FromString,
            response_serializer=DPong.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Scenario', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaScenarioServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Chat(self, request_iterator, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaScenarioStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Chat(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()


  def beta_create_Scenario_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('Scenario', 'Chat'): DPong.FromString,
    }
    response_serializers = {
      ('Scenario', 'Chat'): DPong.SerializeToString,
    }
    method_implementations = {
      ('Scenario', 'Chat'): face_utilities.stream_stream_inline(servicer.Chat),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Scenario_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('Scenario', 'Chat'): DPong.SerializeToString,
    }
    response_deserializers = {
      ('Scenario', 'Chat'): DPong.FromString,
    }
    cardinalities = {
      'Chat': cardinality.Cardinality.STREAM_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'Scenario', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
