# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import scenario_pb2 as scenario__pb2


class ScenarioStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Chat = channel.stream_stream(
        '/Scenario/Chat',
        request_serializer=scenario__pb2.DPong.SerializeToString,
        response_deserializer=scenario__pb2.DPong.FromString,
        )


class ScenarioServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Chat(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ScenarioServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Chat': grpc.stream_stream_rpc_method_handler(
          servicer.Chat,
          request_deserializer=scenario__pb2.DPong.FromString,
          response_serializer=scenario__pb2.DPong.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Scenario', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
